import type { Metadata } from "next";
import "./ui/globals.scss";
import "./tailwind.css";
import Providers from "./providers";
import Navbar from "./components/navbar";
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${quicksand.className}  antialiased`}
      >
        <main>
          <Providers>
            <Navbar/>
            {children}
          </Providers>
        </main>
        
      </body>
    </html>
  );
}
